const actionName = {
  LOADING: "loading",
  USER_LIST : "USER_LIST",
  USER_PROFILE : "USER_PROFILE",
  USER_COUNTER : "USER_COUNTER",
  GET_REQUEST : "GET_REQUEST",
  GET_INFLUENCER : "GET_INFLUENCER",
  GET_INFLUENCER_EXIST : "GET_INFLUENCER_EXIST",
  GET_INFLUENCER_STATS : "GET_INFLUENCER_STATS",
  GET_DEFAULT_MSG : "GET_DEFAULT_MSG",
  GET_ALL_DATES: "GET_ALL_DATES"
};

export default actionName;
